version: "3.8"

services:
  app:
    build: .
    volumes:
      - ./:/app
    ports:
      - "8000:8000"

  nginx:
    image: nginx
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - app
